import { getThemeHex, isDashboardPaletteTheme } from '../config/themeOptions';

const useThemeStyles = (theme) => {
    const styles = {
        textColor: {
            'bg-skin-blue': 'text-black',
            'bg-skin-blue-light': 'text-black',
            'bg-skin-yellow': 'text-black',
            'bg-skin-yellow-light': 'text-black',
            'bg-skin-green': 'text-black',
            'bg-skin-green-light': 'text-black',
            'bg-skin-purple': 'text-black',
            'bg-skin-purple-light': 'text-black',
            'bg-skin-red': 'text-black',
            'bg-skin-red-light': 'text-black',
            'bg-skin-black': 'text-gray-300',
            'bg-skin-black-light': 'text-black',
            'bg-skin-white': 'text-black',
        },
        hoverTextColor: {
            'bg-skin-blue': 'hover:text-white',
            'bg-skin-blue-light': 'hover:text-white',
            'bg-skin-yellow': 'hover:text-white',
            'bg-skin-yellow-light': 'hover:text-white',
            'bg-skin-green': 'hover:text-white',
            'bg-skin-green-light': 'hover:text-white',
            'bg-skin-purple': 'hover:text-white',
            'bg-skin-purple-light': 'hover:text-white',
            'bg-skin-red': 'hover:text-white',
            'bg-skin-red-light': 'hover:text-white',
            'bg-skin-black': 'hover:text-gray-100',
            'bg-skin-black-light': 'hover:text-black',
            'bg-skin-white': 'hover:text-white',
        },
        hoverBgColor: {
            'bg-skin-blue': 'hover:bg-gray-100',
            'bg-skin-blue-light': 'hover:bg-gray-100',
            'bg-skin-yellow': 'hover:bg-white',
            'bg-skin-yellow-light': 'hover:bg-white',
            'bg-skin-green': 'hover:bg-white',
            'bg-skin-green-light': 'hover:bg-white',
            'bg-skin-purple': 'hover:bg-white',
            'bg-skin-purple-light': 'hover:bg-white',
            'bg-skin-red': 'hover:bg-white',
            'bg-skin-red-light': 'hover:bg-white',
            'bg-skin-black': 'hover:bg-skin-black',
            'bg-skin-black-light': 'hover:bg-black',
            'bg-skin-white': 'hover:bg-gray-100',
        },
        textColorActive: {
            'bg-skin-blue': 'text-white',
            'bg-skin-blue-light': 'text-white',
            'bg-skin-yellow': 'text-white',
            'bg-skin-yellow-light': 'text-white',
            'bg-skin-green': 'text-white',
            'bg-skin-green-light': 'text-white',
            'bg-skin-purple': 'text-white',
            'bg-skin-purple-light': 'text-white',
            'bg-skin-red': 'text-white',
            'bg-skin-red-light': 'text-white',
            'bg-skin-black': 'text-gray-400',
            'bg-skin-black-light': 'text-black',
            'bg-skin-white': 'text-white',
        },
        bgColor: {
            'bg-skin-blue': 'bg-white',
            'bg-skin-blue-light': 'bg-white',
            'bg-skin-yellow': 'bg-white',
            'bg-skin-yellow-light': 'bg-white',
            'bg-skin-green': 'bg-white',
            'bg-skin-green-light': 'bg-white',
            'bg-skin-purple': 'bg-white',
            'bg-skin-purple-light': 'bg-white',
            'bg-skin-red': 'bg-white',
            'bg-skin-red-light': 'bg-white',
            'bg-skin-black': 'bg-black-table-color',
            'bg-skin-black-light': 'bg-skin-black',
            'bg-skin-white': 'bg-white',
        },
        borderColor: {
            'bg-skin-blue': 'border-white',
            'bg-skin-blue-light': 'border-white',
            'bg-skin-yellow': 'border-white',
            'bg-skin-yellow-light': 'border-white',
            'bg-skin-green': 'border-white',
            'bg-skin-green-light': 'border-white',
            'bg-skin-purple': 'border-white',
            'bg-skin-purple-light': 'border-white',
            'bg-skin-red': 'border-white',
            'bg-skin-red-light': 'border-white',
            'bg-skin-black': 'border-gray-400',
            'bg-skin-black-light': 'border-white',
            'bg-skin-white': 'border-gray-400',
        },
        tooltipColor: {
            "skin-blue": "bg-skin-blue-light",
            "skin-blue-light": "bg-skin-blue",
            "skin-yellow": "bg-skin-yellow-light",
            "skin-yellow-light": "bg-skin-yellow",
            "skin-green": "bg-skin-green-light",
            "skin-green-light": "bg-green-yellow",
            "skin-purple": "bg-skin-purple-light",
            "skin-purple-light": "bg-skin-purple",
            "skin-red": "bg-skin-red-light",
            "skin-red-light": "bg-skin-red",
            "skin-black": "bg-skin-black-light",
            "skin-black-light": "bg-skin-black",
            "skin-white": 'bg-skin-white-light',
        },
        arrwoTooltipColor: {
            'skin-blue': '#508C9B',
            'skin-blue-light': '#134B70',
            'skin-yellow': '#FFF455',
            'skin-yellow-light': '#F4CE14',
            'skin-green': '#508D4E',
            'skin-green-light': '#1A5319',
            'skin-purple': '#BC5A94',
            'skin-purple-light': '#F075AA',
            'skin-red': '#E72929',
            'skin-red-light': '#C40C0C',
            'skin-black': '#31363F',
            'skin-black-light': '#322C2B',
            'skin-white': '#e9f3f5',
        },
        buttonSwalColor: {
            'bg-skin-blue': '#134B70',
            'bg-skin-blue-light': '#508C9B',
            'bg-skin-yellow': '#F4CE14',
            'bg-skin-yellow-light': '#FFF455',
            'bg-skin-green': '#1A5319',
            'bg-skin-green-light': '#508D4E',
            'bg-skin-purple': '#BC5A94',
            'bg-skin-purple-light': '#F075AA',
            'bg-skin-red': '#C40C0C',
            'bg-skin-red-light': '#E72929',
            'bg-skin-black': '#322C2B',
            'bg-skin-black-light': '#31363F',
            'bg-skin-white': '#60A5FA',
        },
        paginationHoverColor: {
            "bg-skin-blue": "hover:bg-skin-blue-light",
            "bg-skin-blue-light": "hover:bg-skin-blue",
            "bg-skin-yellow": "hover:bg-skin-yellow-light",
            "bg-skin-yellow-light": "hover:bg-skin-yellow",
            "bg-skin-green": "hover:bg-skin-green-light",
            "bg-skin-green-light": "hover:bg-skin-green",
            "bg-skin-purple": "hover:bg-skin-purple-light",
            "bg-skin-purple-light": "hover:bg-skin-purple",
            "bg-skin-red": "hover:bg-skin-red-light",
            "bg-skin-red-light": "hover:bg-skin-red",
            "bg-skin-black": "hover:bg-skin-black-light",
            "bg-skin-black-light": "hover:bg-skin-black",
            "bg-skin-white": "hover:bg-skin-white-light",
        },
        hoverColor: {
            "bg-skin-blue": "hover:bg-skin-blue",
            "bg-skin-blue-light": "hover:bg-skin-blue-light",
            "bg-skin-yellow": "hover:bg-skin-yellow",
            "bg-skin-yellow-light": "hover:bg-skin-yellow-light",
            "bg-skin-green": "hover:bg-skin-green",
            "bg-skin-green-light": "hover:bg-skin-green-light",
            "bg-skin-purple": "hover:bg-skin-purple",
            "bg-skin-purple-light": "hover:bg-skin-purple-light",
            "bg-skin-red": "hover:bg-skin-red",
            "bg-skin-red-light": "hover:bg-skin-red-light",
            "bg-skin-black": "hover:bg-skin-black-hover",
            "bg-skin-black-light": "hover:bg-skin-black-light",
            "bg-skin-white": "hover:bg-skin-black",
        },
        primayActiveColor: {
            "bg-skin-blue": "bg-skin-blue-light",
            "bg-skin-blue-light": "bg-skin-blue",
            "bg-skin-yellow": "bg-skin-yellow-light",
            "bg-skin-yellow-light": "bg-skin-yellow",
            "bg-skin-green": "bg-skin-green-light",
            "bg-skin-green-light": "bg-skin-green",
            "bg-skin-purple": "bg-skin-purple-light",
            "bg-skin-purple-light": "bg-skin-purple",
            "bg-skin-red": "bg-skin-red-light",
            "bg-skin-red-light": "bg-skin-red",
            "bg-skin-black": "bg-skin-white",
            "bg-skin-black-light": "bg-skin-black",
            "bg-skin-white": "bg-skin-black"
        },
        paginationSideActiveColor: {
            "bg-skin-blue": "bg-skin-blue-light",
            "bg-skin-blue-light": "bg-skin-blue",
            "bg-skin-yellow": "bg-skin-yellow-light",
            "bg-skin-yellow-light": "bg-skin-yellow",
            "bg-skin-green": "bg-skin-green-light",
            "bg-skin-green-light": "bg-skin-green",
            "bg-skin-purple": "bg-skin-purple-light",
            "bg-skin-purple-light": "bg-skin-purple",
            "bg-skin-red": "bg-skin-red-light",
            "bg-skin-red-light": "bg-skin-red",
            "bg-skin-black": "bg-skin-black-light",
            "bg-skin-black-light": "bg-skin-black",
            "bg-skin-white": "bg-skin-white-light"
        },
        borderTheme: {
            'bg-skin-blue': 'border-teal-500',
            'bg-skin-blue-light': 'border-cyan-700',
            'bg-skin-yellow': 'border-yellow-500',
            'bg-skin-yellow-light': 'border-yellow-400',
            'bg-skin-green': 'border-green-500',
            'bg-skin-green-light': 'border-green-400',
            'bg-skin-purple': 'border-fuchsia-400',
            'bg-skin-purple-light': 'border-fuchsia-400',
            'bg-skin-red': 'border-red-500',
            'bg-skin-red-light': 'border-red-400',
            'bg-skin-black': 'border-black',
            'bg-skin-black-light': 'border-black',
            'bg-skin-white': 'border-blue-300',
        },
        secondaryHoverBorderTheme: {
            'bg-skin-blue': 'hover:border-teal-500',
            'bg-skin-blue-light': 'hover:border-cyan-700',
            'bg-skin-yellow': 'hover:border-yellow-500',
            'bg-skin-yellow-light': 'hover:border-yellow-400',
            'bg-skin-green': 'hover:border-green-500',
            'bg-skin-green-light': 'hover:border-green-400',
            'bg-skin-purple': 'hover:border-fuchsia-400',
            'bg-skin-purple-light': 'hover:border-fuchsia-400',
            'bg-skin-red': 'hover:border-red-500',
            'bg-skin-red-light': 'hover:border-red-400',
            'bg-skin-black': 'hover:border-black',
            'bg-skin-black-light': 'hover:border-black',
            'bg-skin-white': 'hover:border-blue-300',
        },

        calendarDateTimeColor: {
            'bg-skin-blue': 'bg-skin-white-light',
            'bg-skin-blue-light': 'bg-skin-white',
            'bg-skin-yellow': 'bg-skin-yellow-light',
            'bg-skin-yellow-light': 'bg-skin-yellow',
            'bg-skin-green': 'bg-skin-green-light',
            'bg-skin-green-light': 'bg-skin-green',
            'bg-skin-purple': 'bg-skin-purple-light',
            'bg-skin-purple-light': 'bg-skin-purple',
            'bg-skin-red': 'bg-skin-red-light',
            'bg-skin-red-light': 'bg-skin-red',
            'bg-skin-black': 'bg-skin-black-hover',
            'bg-skin-black-light': 'bg-skin-black',
            'bg-skin-white': 'bg-skin-white-light',
        },
        calendarDateTimeTextColor: {
            'bg-skin-blue': 'text-gray-900',
            'bg-skin-blue-light': 'text-gray-900',
            'bg-skin-yellow': 'text-gray-900',
            'bg-skin-yellow-light': 'text-gray-900',
            'bg-skin-green': 'text-gray-900',
            'bg-skin-green-light': 'text-gray-900',
            'bg-skin-purple': 'text-gray-900',
            'bg-skin-purple-light': 'text-gray-900',
            'bg-skin-red': 'text-white',
            'bg-skin-red-light': 'text-white',
            'bg-skin-black': 'text-gray-200',
            'bg-skin-black-light': 'text-gray-200',
            'bg-skin-white': 'text-gray-900',
        },

        iconThemeColor : {
            'bg-skin-blue': 'text-sky-900',
            'bg-skin-blue-light': 'text-cyan-800',
            'bg-skin-yellow': 'text-amber-600',
            'bg-skin-yellow-light': 'text-amber-300',
            'bg-skin-green': 'text-green-700',
            'bg-skin-green-light': 'text-green-700',
            'bg-skin-purple': 'text-pink-800',
            'bg-skin-purple-light': 'text-pink-600',
            'bg-skin-red': 'text-red-600',
            'bg-skin-red-light': 'text-red-600',
            'bg-skin-black': 'text-gray-400',
            'bg-skin-black-light': 'text-gray-800',
            'bg-skin-white': 'text-sky-700',
        },
        scrollbarTheme: {
            'bg-skin-blue': 'scrollbar-thumb-sky-900',
            'bg-skin-blue-light': 'scrollbar-thumb-cyan-800',
            'bg-skin-yellow': 'scrollbar-thumb-amber-600',
            'bg-skin-yellow-light': 'scrollbar-thumb-amber-300',
            'bg-skin-green': 'scrollbar-thumb-green-700',
            'bg-skin-green-light': 'scrollbar-thumb-green-700',
            'bg-skin-purple': 'scrollbar-thumb-pink-800',
            'bg-skin-purple-light': 'scrollbar-thumb-pink-600',
            'bg-skin-red': 'scrollbar-thumb-red-600',
            'bg-skin-red-light': 'scrollbar-thumb-red-600',
            'bg-skin-black': 'scrollbar-thumb-gray-900',
            'bg-skin-black-light': 'scrollbar-thumb-gray-800',
            'bg-skin-white': 'scrollbar-thumb-sky-700',
        },

        bulkActionTextColor: {
            'bg-skin-blue': 'text-skin-blue-secondary',
            'bg-skin-black': 'text-gray-300',
        
        },


        bulkActionCancelButtonColor: {
            'bg-skin-blue': 'bg-gray-200',
            'bg-skin-black': 'bg-gray-200',
         
        },

        // SIDEBAR
        sidebarHoverTextColor: {
            'bg-skin-blue':         'hover:text-white',
            'bg-skin-blue-light':   'hover:text-white',
            'bg-skin-yellow':       'hover:text-white',
            'bg-skin-yellow-light': 'hover:text-white',
            'bg-skin-green':        'hover:text-white',
            'bg-skin-green-light':  'hover:text-white',
            'bg-skin-purple':       'hover:text-white',
            'bg-skin-purple-light': 'hover:text-white',
            'bg-skin-red':          'hover:text-white',
            'bg-skin-red-light':    'hover:text-white',
            'bg-skin-black':        'hover:text-white',
            'bg-skin-white':        'hover:text-white',
        },
        sidebarHoverMenuBgColor: {
            'bg-skin-blue':         'hover:bg-skin-blue',
            'bg-skin-blue-light':   'hover:bg-skin-blue-light',
            'bg-skin-yellow':       'hover:bg-skin-yellow',
            'bg-skin-yellow-light': 'hover:bg-skin-yellow-light',
            'bg-skin-green':        'hover:bg-skin-green',
            'bg-skin-green-light':  'hover:bg-skin-green-light',
            'bg-skin-purple':       'hover:bg-skin-purple',
            'bg-skin-purple-light': 'hover:bg-skin-purple-light',
            'bg-skin-red':          'hover:bg-skin-red',
            'bg-skin-red-light':    'hover:bg-skin-red-light',
            'bg-skin-black':        'hover:bg-skin-black',
            'bg-skin-white':        'hover:bg-skin-black',
        },
        sidebarHoverMenuBorderColor: {
            'bg-skin-blue':         'hover:border-skin-blue-light',
            'bg-skin-blue-light':   'hover:border-skin-blue-light',
            'bg-skin-yellow':       'hover:border-skin-yellow-light',
            'bg-skin-yellow-light': 'hover:border-skin-yellow-light',
            'bg-skin-green':        'hover:border-skin-green',
            'bg-skin-green-light':  'hover:border-skin-green-light',
            'bg-skin-purple':       'hover:border-skin-purple',
            'bg-skin-purple-light': 'hover:border-skin-purple-light',
            'bg-skin-red':          'hover:border-skin-red',
            'bg-skin-red-light':    'hover:border-skin-red-light',
            'bg-skin-black':        'hover:border-skin-black-light',
            'bg-skin-white':        'hover:border-skin-black-light',
        },

        sidebarActiveTextColor: {
            'bg-skin-blue':         'text-white',
            'bg-skin-blue-light':   'text-white',
            'bg-skin-yellow':       'text-white',
            'bg-skin-yellow-light': 'text-white',
            'bg-skin-green':        'text-white',
            'bg-skin-green-light':  'text-white',
            'bg-skin-purple':       'text-white',
            'bg-skin-purple-light': 'text-white',
            'bg-skin-red':          'text-white',
            'bg-skin-red-light':    'text-white',
            'bg-skin-black':        'text-white',
            'bg-skin-white':        'text-white',
        },
        sidebarActiveMenuBgColor: {
            'bg-skin-blue':         'bg-skin-blue',
            'bg-skin-blue-light':   'bg-skin-blue-light',
            'bg-skin-yellow':       'bg-skin-yellow',
            'bg-skin-yellow-light': 'bg-skin-yellow-light',
            'bg-skin-green':        'bg-skin-green',
            'bg-skin-green-light':  'bg-skin-green-light',
            'bg-skin-purple':       'bg-skin-purple',
            'bg-skin-purple-light': 'bg-skin-purple-light',
            'bg-skin-red':          'bg-skin-red',
            'bg-skin-red-light':    'bg-skin-red-light',
            'bg-skin-black':        'bg-skin-black',
            'bg-skin-white':        'bg-skin-black',
        },
        sidebarActiveMenuBorderColor: {
            'bg-skin-blue':         'border-skin-blue-light',
            'bg-skin-blue-light':   'border-skin-blue-light',
            'bg-skin-yellow':       'border-skin-yellow-light',
            'bg-skin-yellow-light': 'border-skin-yellow-light',
            'bg-skin-green':        'border-skin-green-light',
            'bg-skin-green-light':  'border-skin-green-light',
            'bg-skin-purple':       'border-skin-purple-light',
            'bg-skin-purple-light': 'border-skin-purple-light',
            'bg-skin-red':          'border-skin-red-light',
            'bg-skin-red-light':    'border-skin-red-light',
            'bg-skin-black':        'border-skin-black-light',
            'bg-skin-white':        'border-skin-white-light',
        },
        sidebarBorderColor: {
            'bg-skin-blue':         'border-white',
            'bg-skin-blue-light':   'border-white',
            'bg-skin-yellow':       'border-white',
            'bg-skin-yellow-light': 'border-white',
            'bg-skin-green':        'border-white',
            'bg-skin-green-light':  'border-white',
            'bg-skin-purple':       'border-white',
            'bg-skin-purple-light': 'border-white',
            'bg-skin-red':          'border-white',
            'bg-skin-red-light':    'border-white',
            'bg-skin-black':        'border-black-table-color',
            'bg-skin-white':        'border-white',
        },

        sideBarTextColor: {
            'bg-skin-blue':         'text-gray-900',
            'bg-skin-blue-light':   'text-gray-900',
            'bg-skin-yellow':       'text-gray-900',
            'bg-skin-yellow-light': 'text-gray-900',
            'bg-skin-green':        'text-gray-900',
            'bg-skin-green-light':  'text-gray-900',
            'bg-skin-purple':       'text-gray-900',
            'bg-skin-purple-light': 'text-gray-900',
            'bg-skin-red':          'text-gray-900',
            'bg-skin-red-light':    'text-gray-900',
            'bg-skin-black':        'text-white',
            'bg-skin-white':        'text-black',
        },

        sideBarBgColor: {
            'bg-skin-blue':         'bg-white',
            'bg-skin-blue-light':   'bg-white',
            'bg-skin-yellow':       'bg-white',
            'bg-skin-yellow-light': 'bg-white',
            'bg-skin-green':        'bg-white',
            'bg-skin-green-light':  'bg-white',
            'bg-skin-purple':       'bg-white',
            'bg-skin-purple-light': 'bg-white',
            'bg-skin-red':          'bg-white',
            'bg-skin-red-light':    'bg-white',
            'bg-skin-black':        'bg-black-table-color',
            'bg-skin-white':        'bg-white',
        },

        whiteBgCoror : {
            'bg-skin-white':        'bg-skin-black',
        }

    };

    // Dashboard-palette and custom-hex themes don't have literal entries in
    // the dictionaries above (those are keyed by the 13 legacy skins) --
    // this fallback set covers them via the CSS-var-backed utility classes
    // and Tailwind's real `skin-palette-*`/`skin-custom` colors instead.
    const usesModernPalette = isDashboardPaletteTheme(theme) || theme === 'bg-skin-custom';
    const themeFallbacks = {
        textColor: 'text-black',
        textColorActive: usesModernPalette ? 'text-theme-contrast' : 'text-white',
        hoverTextColor: 'hover:text-white',
        hoverBgColor: 'hover:bg-gray-100',
        bgColor: 'bg-white',
        borderColor: 'border-white',
        tooltipColor: theme || 'bg-skin-blue',
        arrwoTooltipColor: getThemeHex(theme) || '#3B82F6',
        buttonSwalColor: getThemeHex(theme) || '#3B82F6',
        paginationHoverColor: 'hover:brightness-90',
        primayActiveColor: theme || 'bg-skin-blue',
        paginationSideActiveColor: theme || 'bg-skin-blue',
        hoverColor: 'hover:brightness-90',
        borderTheme: 'border-gray-300',
        secondaryHoverBorderTheme: 'hover:border-gray-400',
        calendarDateTimeColor: theme || 'bg-skin-blue',
        calendarDateTimeTextColor: usesModernPalette ? 'text-theme-contrast' : 'text-gray-900',
        iconThemeColor: 'text-slate-700',
        scrollbarTheme: 'scrollbar-thumb-slate-500',
        bulkActionTextColor: 'text-gray-900',
        bulkActionCancelButtonColor: 'bg-gray-200',
        sideBarTextColor: 'text-gray-900',
        sideBarBgColor: 'bg-white',
        sidebarHoverTextColor: 'sidebar-theme-hover-text',
        sidebarHoverMenuBgColor: 'sidebar-theme-hover-bg',
        sidebarHoverMenuBorderColor: 'sidebar-theme-hover-border',
        sidebarActiveTextColor: usesModernPalette ? 'text-theme-contrast' : 'text-white',
        sidebarActiveMenuBgColor: theme || 'bg-skin-blue',
        sidebarActiveMenuBorderColor: 'border-white',
        sidebarBorderColor: 'border-white',
        whiteBgCoror: '',
    };
    const value = (key) => styles[key][theme] ?? themeFallbacks[key];

    return {
        textColor:                    value('textColor'),
        textColorActive:              value('textColorActive'),
        hoverTextColor:               value('hoverTextColor'),
        hoverBgColor:                 value('hoverBgColor'),
        bgColor:                      value('bgColor'),
        borderColor:                  value('borderColor'),
        tooltipColor:                 value('tooltipColor'),
        arrwoTooltipColor:            value('arrwoTooltipColor'),
        buttonSwalColor:              value('buttonSwalColor'),
        paginationHoverColor:         value('paginationHoverColor'),
        primayActiveColor:            value('primayActiveColor'),
        paginationSideActiveColor:    value('paginationSideActiveColor'),
        hoverColor:                   value('hoverColor'),
        borderTheme:                  value('borderTheme'),
        secondaryHoverBorderTheme:    value('secondaryHoverBorderTheme'),
        calendarDateTimeColor:        value('calendarDateTimeColor'),
        calendarDateTimeTextColor:    value('calendarDateTimeTextColor'),
        iconThemeColor:               value('iconThemeColor'),
        scrollbarTheme:               value('scrollbarTheme'),
        bulkActionTextColor:          value('bulkActionTextColor'),
        bulkActionCancelButtonColor:  value('bulkActionCancelButtonColor'),
        sideBarTextColor:             value('sideBarTextColor'),
        sideBarBgColor:               value('sideBarBgColor'),
        sidebarHoverTextColor:        value('sidebarHoverTextColor'),
        sidebarHoverMenuBgColor:      value('sidebarHoverMenuBgColor'),
        sidebarHoverMenuBorderColor:  value('sidebarHoverMenuBorderColor'),
        sidebarActiveTextColor:       value('sidebarActiveTextColor'),
        sidebarActiveMenuBgColor:     value('sidebarActiveMenuBgColor'),
        sidebarActiveMenuBorderColor: value('sidebarActiveMenuBorderColor'),
        sidebarBorderColor:           value('sidebarBorderColor'),
        whiteBgCoror:                 value('whiteBgCoror'),
    };
};

export default useThemeStyles;
