"""Create Adm Password History Table

Revision ID: 022ba142afa7
Revises: f553ec35b64a
Create Date: 2026-09-08 16:53:54.737408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022ba142afa7'
down_revision: Union[str, Sequence[str], None] = 'f553ec35b64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adm_user_id', sa.Integer(), nullable=True),
    sa.Column('adm_user_old_pass', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adm_password_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adm_password_history_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adm_password_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adm_password_history_id'))

    op.drop_table('adm_password_history')
    # ### end Alembic commands ###
