"""add token_version to adm_users

Revision ID: 15ec4b269023
Revises: dc5e59e6b124
Create Date: 2026-08-28 16:50:12.758393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ec4b269023'
down_revision: Union[str, Sequence[str], None] = 'dc5e59e6b124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adm_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adm_users', schema=None) as batch_op:
        batch_op.drop_column('token_version')

    # ### end Alembic commands ###
