"""Create Adm Settings Table

Revision ID: 1c920f3f3d99
Revises: 6a0712d68f1b
Create Date: 2026-09-06 17:39:13.986404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c920f3f3d99'
down_revision: Union[str, Sequence[str], None] = '6a0712d68f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_input_type', sa.String(length=255), nullable=True),
    sa.Column('dataenum', sa.String(length=255), nullable=True),
    sa.Column('helper', sa.String(length=255), nullable=True),
    sa.Column('group_setting', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adm_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adm_settings_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adm_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adm_settings_id'))

    op.drop_table('adm_settings')
    # ### end Alembic commands ###
