"""create chat_conversations table

Revision ID: 1e7f9e38cbd1
Revises: 022ba142afa7
Create Date: 2026-09-10 15:07:55.919099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7f9e38cbd1'
down_revision: Union[str, Sequence[str], None] = '022ba142afa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adm_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('recent_messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adm_user_id'], ['adm_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_conversations_adm_user_id'), ['adm_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_conversations_id'))
        batch_op.drop_index(batch_op.f('ix_chat_conversations_adm_user_id'))

    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
