"""menus parent_id self-reference, drop module fk

Revision ID: 253f97ec1dfd
Revises: cdf659bd13b9
Create Date: 2026-08-30 17:38:54.401867

Hand-written, not autogenerated: alembic reads a column rename as
"drop patent_id, add parent_id", which would throw the data away. The
column is renamed in place instead.

adm_menuses.patent_id used to be a foreign key into adm_modules. A menu's
parent is another *menu* (an accordion group), so the column now points at
adm_menuses.id. Existing values are ids from a different table entirely,
which makes them meaningless here -- and any value with no matching menu id
would fail the new constraint -- so they are cleared before it is added.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253f97ec1dfd'
down_revision: Union[str, Sequence[str], None] = 'cdf659bd13b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint("adm_menuses_patent_id_fkey", "adm_menuses", type_="foreignkey")
    op.alter_column("adm_menuses", "patent_id", new_column_name="parent_id")
    op.execute("UPDATE adm_menuses SET parent_id = NULL")
    op.create_foreign_key(
        "adm_menuses_parent_id_fkey",
        "adm_menuses",
        "adm_menuses",
        ["parent_id"],
        ["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("adm_menuses_parent_id_fkey", "adm_menuses", type_="foreignkey")
    op.execute("UPDATE adm_menuses SET parent_id = NULL")
    op.alter_column("adm_menuses", "parent_id", new_column_name="patent_id")
    op.create_foreign_key(
        "adm_menuses_patent_id_fkey",
        "adm_menuses",
        "adm_modules",
        ["patent_id"],
        ["id"],
    )
