"""Adm Roles Privileges table

Revision ID: 6a0712d68f1b
Revises: 4a53b9d60757
Create Date: 2026-09-02 16:57:49.939348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0712d68f1b'
down_revision: Union[str, Sequence[str], None] = '4a53b9d60757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_roles_privileges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Integer(), nullable=True),
    sa.Column('is_create', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.Column('is_edit', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('is_void', sa.Integer(), nullable=True),
    sa.Column('is_override', sa.Integer(), nullable=True),
    sa.Column('id_adm_roles', sa.Integer(), nullable=True),
    sa.Column('id_adm_modules', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adm_roles_privileges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adm_roles_privileges_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adm_roles_privileges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adm_roles_privileges_id'))

    op.drop_table('adm_roles_privileges')
    # ### end Alembic commands ###
