"""add memecoin watch columns and alerts

Phase 9 of the memecoin analyzer: where each watched wallet's last scan stopped,
and the alerts for tokens it gained. The known adm_menus_roles drift that
autogenerate proposed was removed (see docs/vram/migrations.md).

Revision ID: 6bc95dcb68fa
Revises: b33310bd5184
Create Date: 2026-09-27 15:12:42.755623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc95dcb68fa'
down_revision: Union[str, Sequence[str], None] = 'b33310bd5184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memecoin_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('wallet_address', sa.String(length=44), nullable=False),
    sa.Column('wallet_list', sa.String(length=16), nullable=False),
    sa.Column('wallet_label', sa.String(length=100), nullable=True),
    sa.Column('mint', sa.String(length=44), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('signature', sa.String(length=100), nullable=False),
    sa.Column('block_time', sa.DateTime(), nullable=True),
    sa.Column('seen', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['memecoin_wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature', 'wallet_address', 'mint', name='uq_memecoin_alerts_signature_wallet_mint')
    )
    with op.batch_alter_table('memecoin_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memecoin_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memecoin_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memecoin_alerts_wallet_id'), ['wallet_id'], unique=False)

    with op.batch_alter_table('memecoin_wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_signature', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_checked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memecoin_wallets', schema=None) as batch_op:
        batch_op.drop_column('last_checked_at')
        batch_op.drop_column('last_signature')

    with op.batch_alter_table('memecoin_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memecoin_alerts_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_memecoin_alerts_id'))
        batch_op.drop_index(batch_op.f('ix_memecoin_alerts_created_at'))

    op.drop_table('memecoin_alerts')
    # ### end Alembic commands ###
