"""add chain to memecoin trades

The analyzer now covers EVM chains, so a journal trade records its chain.
Existing trades get "solana" from the server default. The known
adm_menus_roles drift that autogenerate proposed was removed.

Revision ID: 8512ed42c0ac
Revises: 6bc95dcb68fa
Create Date: 2026-09-27 15:56:28.929114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8512ed42c0ac'
down_revision: Union[str, Sequence[str], None] = '6bc95dcb68fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memecoin_trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chain', sa.String(length=16), server_default='solana', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memecoin_trades', schema=None) as batch_op:
        batch_op.drop_column('chain')

    # ### end Alembic commands ###
