"""Create adm_menus_roles table

Revision ID: 8cf7b008c9f2
Revises: 219810c6de37
Create Date: 2026-09-15 16:11:11.353019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf7b008c9f2'
down_revision: Union[str, Sequence[str], None] = '219810c6de37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_menus_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_adm_menus', sa.Integer(), nullable=False),
    sa.Column('id_adm_role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_adm_menus'], ['adm_menuses.id'], ),
    sa.ForeignKeyConstraint(['id_adm_role'], ['adm_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adm_menus_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adm_menus_roles_id'), ['id'], unique=False)
        # Laravel has no such constraint and avoids duplicates by diffing in
        # PHP; making it the database's job means a double submit cannot grant
        # the same role twice.
        batch_op.create_unique_constraint(
            'uq_adm_menus_roles_menu_role', ['id_adm_menus', 'id_adm_role']
        )

    # ### end Alembic commands ###

    # Carry the existing one-role-per-menu assignments into the pivot. Without
    # this the sidebar empties the moment /user_sidebar starts reading it.
    op.execute(
        """
        INSERT INTO adm_menus_roles (id_adm_menus, id_adm_role)
        SELECT id, id_adm_role FROM adm_menuses WHERE id_adm_role IS NOT NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adm_menus_roles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_adm_menus_roles_menu_role', type_='unique')
        batch_op.drop_index(batch_op.f('ix_adm_menus_roles_id'))

    op.drop_table('adm_menus_roles')
    # ### end Alembic commands ###
