"""create adm_roles table

Revision ID: 8eb3492f7d7f
Revises: ea4a87ce3d77
Create Date: 2026-08-28 15:49:41.025278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb3492f7d7f'
down_revision: Union[str, Sequence[str], None] = 'ea4a87ce3d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_superadmin', sa.Integer(), nullable=True),
    sa.Column('theme_color', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adm_roles_id'), 'adm_roles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adm_roles_id'), table_name='adm_roles')
    op.drop_table('adm_roles')
    # ### end Alembic commands ###
