"""Create Adm Notifications Table

Revision ID: b2ae01ff82c2
Revises: 7f3d4c2a1b6e
Create Date: 2026-09-08 13:17:53.270479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ae01ff82c2'
down_revision: Union[str, Sequence[str], None] = '7f3d4c2a1b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adm_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adm_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adm_notifications_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adm_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adm_notifications_id'))

    op.drop_table('adm_notifications')
    # ### end Alembic commands ###
