"""create memecoin tables

Saved reports, wallet lists, and the trade journal for the memecoin analyzer
(Phase 6). Autogenerate also proposed dropping uq_adm_menus_roles_menu_role on
adm_menus_roles, which is existing drift unrelated to this change; it was removed.

Revision ID: b33310bd5184
Revises: 8cf7b008c9f2
Create Date: 2026-09-27 14:41:22.030442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33310bd5184'
down_revision: Union[str, Sequence[str], None] = '8cf7b008c9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memecoin_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=44), nullable=False),
    sa.Column('chain', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('adm_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adm_user_id'], ['adm_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memecoin_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memecoin_reports_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_memecoin_reports_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memecoin_reports_id'), ['id'], unique=False)

    op.create_table('memecoin_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=44), nullable=False),
    sa.Column('list', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('adm_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adm_user_id'], ['adm_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list', 'address', name='uq_memecoin_wallets_list_address')
    )
    with op.batch_alter_table('memecoin_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memecoin_wallets_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_memecoin_wallets_id'), ['id'], unique=False)

    op.create_table('memecoin_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adm_user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=44), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=True),
    sa.Column('entry_reason', sa.Text(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('exited_at', sa.DateTime(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adm_user_id'], ['adm_users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['memecoin_reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memecoin_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memecoin_trades_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_memecoin_trades_adm_user_id'), ['adm_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memecoin_trades_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memecoin_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memecoin_trades_id'))
        batch_op.drop_index(batch_op.f('ix_memecoin_trades_adm_user_id'))
        batch_op.drop_index(batch_op.f('ix_memecoin_trades_address'))

    op.drop_table('memecoin_trades')
    with op.batch_alter_table('memecoin_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memecoin_wallets_id'))
        batch_op.drop_index(batch_op.f('ix_memecoin_wallets_address'))

    op.drop_table('memecoin_wallets')
    with op.batch_alter_table('memecoin_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memecoin_reports_id'))
        batch_op.drop_index(batch_op.f('ix_memecoin_reports_checked_at'))
        batch_op.drop_index(batch_op.f('ix_memecoin_reports_address'))

    op.drop_table('memecoin_reports')
    # ### end Alembic commands ###
