"""Create Adm User Profiles Table

Revision ID: c4af3bd01771
Revises: 1c920f3f3d99
Create Date: 2026-09-07 12:06:13.097691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4af3bd01771'
down_revision: Union[str, Sequence[str], None] = '1c920f3f3d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adm_user_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('ext', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('archived', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adm_user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adm_user_profiles_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adm_user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adm_user_profiles_id'))

    op.drop_table('adm_user_profiles')
    # ### end Alembic commands ###
