"""add archived_at to chat_conversations

Revision ID: ccd7b3ed41cf
Revises: 1e7f9e38cbd1
Create Date: 2026-09-11 10:15:23.927695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd7b3ed41cf'
down_revision: Union[str, Sequence[str], None] = '1e7f9e38cbd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
