"""create adm_modules and adm_menuses tables

Revision ID: cdf659bd13b9
Revises: 15ec4b269023
Create Date: 2026-08-28 17:26:24.269608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf659bd13b9'
down_revision: Union[str, Sequence[str], None] = '15ec4b269023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('controller', sa.String(length=255), nullable=True),
    sa.Column('is_protected', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adm_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adm_modules_id'), ['id'], unique=False)

    op.create_table('adm_menuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('patent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('is_dashboard', sa.Integer(), nullable=True),
    sa.Column('id_adm_role', sa.Integer(), nullable=True),
    sa.Column('sorting', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_adm_role'], ['adm_roles.id'], ),
    sa.ForeignKeyConstraint(['patent_id'], ['adm_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adm_menuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adm_menuses_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adm_menuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adm_menuses_id'))

    op.drop_table('adm_menuses')
    with op.batch_alter_table('adm_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adm_modules_id'))

    op.drop_table('adm_modules')
    # ### end Alembic commands ###
