"""add id_adm_role fk to adm_roles

Revision ID: dc5e59e6b124
Revises: 8eb3492f7d7f
Create Date: 2026-08-28 16:04:40.393360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5e59e6b124'
down_revision: Union[str, Sequence[str], None] = '8eb3492f7d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adm_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_adm_role', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_adm_users_id_adm_role_adm_roles', 'adm_roles', ['id_adm_role'], ['id'])
        batch_op.drop_column('id_adm_privileges')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adm_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_adm_privileges', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_adm_users_id_adm_role_adm_roles', type_='foreignkey')
        batch_op.drop_column('id_adm_role')

    # ### end Alembic commands ###
