"""Create Admin Announcements Table

Revision ID: f553ec35b64a
Revises: b2ae01ff82c2
Create Date: 2026-09-08 14:43:12.015427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f553ec35b64a'
down_revision: Union[str, Sequence[str], None] = 'b2ae01ff82c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adm_announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adm_announcements_id'), ['id'], unique=False)

    with op.batch_alter_table('adm_notifications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'adm_users', ['adm_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adm_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('adm_announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adm_announcements_id'))

    op.drop_table('adm_announcements')
    # ### end Alembic commands ###
