"""Menus module -- generated by module_generator.py on 2026-09-01.

Edit this file freely. It is ordinary code: the metadata below was inferred
from `adm_admin_menuses`, and everything else comes from ModuleController.

  table_fields   the list view's columns, in this order
  form_fields    the create/edit form, plus its validation rules
  search_columns the allowlist for ?search=

Hooks available to override: custom_index_query, index_row, before_store,
after_store, before_update, after_update, before_delete, after_delete.
See docs/MODULES.md.
"""
from app.helpers.generated_module import ModuleController
from app.modules.registry import controller


@controller("MenusController")
class MenusController(ModuleController):
    table_name = 'adm_admin_menuses'
    primary_key = 'id'
    default_sort = 'id'
    search_columns = ['name', 'type', 'path', 'slug', 'color', 'icon']
    has_created_at = True
    has_updated_at = True

    table_fields = {
        'id': {
            'label': 'Id',
        },
        'name': {
            'label': 'Name',
        },
        'type': {
            'label': 'Type',
        },
        'path': {
            'label': 'Path',
        },
        'slug': {
            'label': 'Slug',
        },
        'color': {
            'label': 'Color',
        },
        'icon': {
            'label': 'Icon',
        },
        'parent_id': {
            'label': 'Parent Id',
        },
        'is_active': {
            'label': 'Is Active',
        },
        'sorting': {
            'label': 'Sorting',
        },
        'created_at': {
            'label': 'Created At',
        },
        'updated_at': {
            'label': 'Updated At',
        },
    }

    form_fields = {
        'name': {
            'label': 'Name',
            'type': 'text',
            'max': 255,
        },
        'type': {
            'label': 'Type',
            'type': 'text',
            'max': 255,
        },
        'path': {
            'label': 'Path',
            'type': 'text',
            'max': 255,
        },
        'slug': {
            'label': 'Slug',
            'type': 'text',
            'max': 255,
        },
        'color': {
            'label': 'Color',
            'type': 'text',
            'max': 255,
        },
        'icon': {
            'label': 'Icon',
            'type': 'text',
            'max': 255,
        },
        'parent_id': {
            'label': 'Parent Id',
            'type': 'number',
        },
        'is_active': {
            'label': 'Is Active',
            'type': 'number',
        },
        'sorting': {
            'label': 'Sorting',
            'type': 'number',
        },
    }

    actions = {"view": True, "create": True, "edit": True, "delete": True}
