import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import api from "../../../api";
import { useOptionalToast } from "../../../context/ToastContext";
import TableContainer from "../../../components/table/TableContainer";
import Table from "../../../components/table/Table";
import TableHead from "../../../components/table/TableHead";
import TableBody from "../../../components/table/TableBody";
import TableRow from "../../../components/table/TableRow";
import HeadData from "../../../components/table/HeadData";
import RowData from "../../../components/table/RowData";
import RowActions from "../../../components/table/RowActions";
import RowAction from "../../../components/table/RowAction";
import TopPanel from "../../../components/panel/TopPanel";
import ContentPanel from "../../../components/panel/ContentPanel";
import Toast from "../../../components/panel/Toast";
import PrimaryButton from "../../../components/button/PrimaryButton";
import SecondaryButton from "../../../components/button/SecondaryButton";
import InputLabel from "../../../components/form/InputLabel";
import TextInput from "../../../components/form/TextInput";
import Checkbox from "../../../components/form/Checkbox";
import SelectInput from "../../../components/form/SelectInput";
import InputError from "../../../components/form/InputError";

// The shared module runtime -- the equivalent of Laravel's
// resources/js/Pages/AdmVram/VramJsx/GeneratedModulePage.jsx.
//
// DO NOT EDIT THIS FILE FOR ONE MODULE. It renders whatever metadata the
// backend's render_index() sends, so it already works for every module.
// Anything module-specific belongs in a wrapper page (see RolesPage.jsx),
// which passes it in through the props below.
//
// Ported off Inertia: the original called router.visit() / router.reload()
// and a bare axios. Here navigation is React Router's useNavigate(), the
// reload is just load(), and requests go through the shared api instance so
// they carry the bearer token. See docs/MODULES.md.

const defaultCell = (row, column) => String(row[column.key] ?? "—");

// Hoisted: these are pure, and rebuilding them per render was pointless.
const toBoolean = (value, fallback = false) => {
    if (typeof value === 'boolean') return value;
    if (typeof value === 'number') return value === 1;
    if (typeof value === 'string') {
        const normalized = value.trim().toLowerCase();

        if (['false', '0', 'no', 'off', ''].includes(normalized)) return false;
        if (['true', '1', 'yes', 'on'].includes(normalized)) return true;
    }

    return value === undefined || value === null ? fallback : Boolean(value);
};

const booleanMap = (values, defaults) => Object.keys(defaults).reduce((normalized, key) => ({
    ...normalized,
    [key]: toBoolean(values?.[key], defaults[key]),
}), {});

// "{id}" / ":id" -> the row's value. Used for customRowActions' url,
// confirm text, and payload values.
const resolveTemplate = (template, row) => {
  if (typeof template !== "string") return "";
  const lookup = (key) => {
    const value = row?.[key];
    return value === undefined || value === null ? "" : String(value);
  };
  return template
    .replace(/\{(\w+)\}/g, (_, key) => lookup(key))
    .replace(/:(\w+)\b/g, (_, key) => lookup(key));
};

// A payload can be a function of the row, or an object whose string values
// are templates. Anything else is passed through untouched.
const resolvePayload = (payload, row) => {
  if (typeof payload === "function") return payload(row) ?? {};
  if (!payload || typeof payload !== "object") return {};
  return Object.entries(payload).reduce((out, [key, value]) => {
    out[key] = typeof value === "string" ? resolveTemplate(value, row) : value;
    return out;
  }, {});
};

// Mirrors ModuleController.require(), which is `self.actions.get(cap, False)`:
// a capability is on when the key is PRESENT and truthy. That matters because
// a module may declare actions two ways --
//
//   actions = {"view": True, "create": True, ...}          flags
//   actions = {"edit": {"label": "Edit", "icon": "pencil"}} descriptors
//
// -- and a descriptor object is truthy, so it enables the action and also
// carries its label. A key that is simply absent is OFF, which is why
// omitting "create" makes POST /<path>/store return 403.
const capable = (value) => {
  if (value === undefined || value === null || value === false) return false;
  if (typeof value === "number") return value !== 0;
  if (typeof value === "string") return !["", "false", "0", "no", "off"].includes(value.trim().toLowerCase());
  if (Array.isArray(value)) return value.length > 0;
  if (typeof value === "object") return Object.keys(value).length > 0;
  return Boolean(value);
};

// The descriptor half of the above, for labels/icons. {} when the module
// used a plain boolean.
const descriptor = (value) => (value && typeof value === "object" && !Array.isArray(value) ? value : {});

// A field whose type is "checkbox" maps to an integer column in every
// module that has one (adm_roles.is_superadmin), and Postgres rejects a
// boolean written into an integer column -- so send 1/0, not true/false.
const formValue = (config, raw) =>
  config.type === "checkbox" ? (toBoolean(raw) ? 1 : 0) : raw ?? "";

export default function GeneratedModulePage({
  modulePath,          // defaults to the :modulePath route param
  title,               // override the heading (defaults to the module name)
  renderCell,          // (row, column, defaultCell) => node
  renderBeforeTable,   // (data) => node
  renderAfterTable,    // (data) => node
  indexButtons = [],   // [{ label, onClick(reload) }]
  actions,             // client-side mask: { view, create, edit, delete }
  moduleAccess,        // client-side mask: { view, create, update, delete }
  customRowActions,    // [{ label, action, url, method, confirm, payload, visibleWhen, newTab, reload }]
  customRowActionHandlers = {},
  useEditRoute = false, // edit navigates to /<path>/edit/<id> instead of opening the panel
  onToast,             // (message, status) => void -- opt out of the built-in toast
}) {
  const params = useParams();
  const navigate = useNavigate();
  const path = modulePath ?? params.modulePath;

  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const [sort, setSort] = useState({ by: null, dir: "asc" });
  const [toast, setToast] = useState(null);
  const [panel, setPanel] = useState(null);      // { mode, row, values, errors, busy }

  const accessMask = booleanMap(moduleAccess, { view: true, create: true, update: true, delete: true });
  const actionMask = booleanMap(actions, { view: true, create: true, edit: true, delete: true });

  // Three tiers, most specific first: an explicit onToast prop, the app-wide
  // ToastProvider that AppContent mounts, then local state so the component
  // still works standalone (a wrapper page rendered outside the shell).
  // useOptionalToast rather than useToast: the shared provider is mounted by
  // AppContent, but a wrapper page rendered outside the shell has none, and
  // useToast() throws in that case by design.
  const shared = useOptionalToast();
  const handleToast = useCallback((message, status = "success") => {
    if (onToast) return onToast(message, status);
    if (shared) return shared.handleToast(message, status);
    setToast({ message, status });
  }, [onToast, shared]);

  useEffect(() => {
    if (!toast) return;
    const timer = setTimeout(() => setToast(null), 4000);
    return () => clearTimeout(timer);
  }, [toast]);

  const load = useCallback(() => {
    if (!path) {
      setError("No module specified.");
      setLoading(false);
      return;
    }
    setLoading(true);
    api
      .get(`/${path}`, {
        params: {
          search: search || undefined,
          page,
          sort_by: sort.by || undefined,
          sort_dir: sort.dir,
        },
      })
      .then((res) => {
        setData(res.data);
        setError("");
      })
      .catch((err) =>
        setError(
          err.response?.status === 404
            ? "That module does not exist."
            : err.response?.data?.detail || "Could not load this module."
        )
      )
      .finally(() => setLoading(false));
  }, [path, search, page, sort]);

  useEffect(() => {
    load();
  }, [load]);

  // A new module or a new search term starts again at page 1.
  useEffect(() => {
    setPage(1);
  }, [path, search]);

  const formFields = useMemo(() => data?.formFields ?? {}, [data]);

  const blankValues = useCallback(
    () => Object.fromEntries(Object.entries(formFields).map(([name, cfg]) => [name, formValue(cfg, "")])),
    [formFields]
  );

  const rowValues = useCallback(
    (row) => Object.fromEntries(Object.entries(formFields).map(([name, cfg]) => [name, formValue(cfg, row?.[name])])),
    [formFields]
  );

  const openView = (row) => setPanel({ mode: "view", row, values: rowValues(row), errors: {} });
  const openEdit = (row) => setPanel({ mode: "edit", row, values: rowValues(row), errors: {} });
  const openCreate = () => setPanel({ mode: "create", row: null, values: blankValues(), errors: {} });
  const closePanel = () => setPanel(null);

  // /<path>/edit/<id> -- the route form of edit, for useEditRoute. The record
  // has to be on the page that just loaded; paging to it is not implemented.
  useEffect(() => {
    if (!data || params.moduleAction !== "edit" || !params.recordId) return;
    const match = data.rows.find((r) => String(r[data.primaryKey]) === String(params.recordId));
    if (match) openEdit(match);
    else handleToast(`Record ${params.recordId} is not on this page.`, "danger");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data, params.moduleAction, params.recordId]);

  const toggleSort = (key) =>
    setSort((prev) =>
      prev.by === key
        ? { by: key, dir: prev.dir === "asc" ? "desc" : "asc" }
        : { by: key, dir: "asc" }
    );

  // Turn the backend's error shape into { field: message }. validate() sends
  // a field-keyed dict for 422; everything else sends a plain string.
  const errorsFrom = (err) => {
    const detail = err.response?.data?.detail;
    if (detail && typeof detail === "object" && !Array.isArray(detail)) return detail;
    return {};
  };
  const messageFrom = (err, fallback) => {
    const detail = err.response?.data?.detail;
    if (typeof detail === "string") return detail;
    if (detail && typeof detail === "object") return "Please check the highlighted fields.";
    return fallback;
  };

  const submitPanel = async (event) => {
    event.preventDefault();
    if (!panel || panel.mode === "view") return;
    const isCreate = panel.mode === "create";
    const body = { ...panel.values };
    if (!isCreate) body[data.primaryKey] = panel.row[data.primaryKey];

    setPanel((p) => ({ ...p, busy: true, errors: {} }));
    try {
      const res = await api.post(`/${path}/${isCreate ? "store" : "update"}`, body);
      handleToast(res.data?.message || (isCreate ? "Data saved." : "Data updated."), res.data?.status || "success");
      setPanel(null);
      load();
    } catch (err) {
      setPanel((p) => ({ ...p, busy: false, errors: errorsFrom(err) }));
      handleToast(messageFrom(err, isCreate ? "Could not save." : "Could not update."), "danger");
    }
  };

  const handleDelete = async (row) => {
    const label = row?.name ?? row?.[data.primaryKey];
    if (!window.confirm(`Delete "${label}"? This cannot be undone.`)) return;
    try {
      const res = await api.post(`/${path}/delete`, { [data.primaryKey]: row[data.primaryKey] });
      handleToast(res.data?.message || "Data deleted.", res.data?.status || "success");
      load();
    } catch (err) {
      handleToast(messageFrom(err, "Could not delete."), "danger");
    }
  };

  const rowActionIsVisible = (button, row) => {
      if (button.visible === false) return false;
      if (!button.visibleWhen || typeof button.visibleWhen !== 'object') return true;

      return Object.entries(button.visibleWhen).every(([field, expected]) => {
          const actual = row?.[field];
          const accepted = Array.isArray(expected) ? expected : [expected];
          return accepted.some((value) => String(value) === String(actual));
      });
  };

  const handleCustomRowAction = async (button, row) => {
      const buttonAction = String(button.action || '').toLowerCase();

      if (buttonAction && typeof customRowActionHandlers[buttonAction] === 'function') {
          await customRowActionHandlers[buttonAction](button, row);
          return;
      }

      if (button.confirm && !window.confirm(resolveTemplate(button.confirm, row))) {
          return;
      }

      const url = resolveTemplate(button.url || '', row);

      if (!url) {
          return;
      }

      if ((button.method || 'get').toLowerCase() === 'post') {
          try {
              const response = await api.post(url, resolvePayload(button.payload, row));
              handleToast(response.data?.message || `${button.label || 'Action'} completed.`, response.data?.status || 'success');
              if (button.reload !== false) {
                  load();
              }
          } catch (error) {
              handleToast(messageFrom(error, `${button.label || 'Action'} failed.`), 'danger');
          }
          return;
      }

      if (button.newTab) {
          window.open(url, '_blank', 'noopener,noreferrer');
          return;
      }

      navigate(url);
  };

  if (error) return <p className="error">{error}</p>;
  if (!data) return <p className="muted">Loading…</p>;

  const { columns, rows, pagination, primaryKey } = data;
  const cell = renderCell ?? defaultCell;
  const buttons = customRowActions || [];

  // The server's declaration is the real answer -- read exactly the way
  // require() reads it, with no default-true fallback, so the UI never offers
  // a button the backend will 403. The two prop masks can only take
  // capability away, never grant it.
  const serverActions = {
    view: capable(data.actions?.view),
    create: capable(data.actions?.create),
    edit: capable(data.actions?.edit),
    delete: capable(data.actions?.delete),
  };
  const can = {
    view:   actionMask.view   && accessMask.view   && serverActions.view,
    create: actionMask.create && accessMask.create && serverActions.create,
    edit:   actionMask.edit   && accessMask.update && serverActions.edit,
    delete: actionMask.delete && accessMask.delete && serverActions.delete,
  };
  // A descriptor may carry {label, icon}; a boolean carries nothing.
  const meta = {
    view: descriptor(data.actions?.view),
    edit: descriptor(data.actions?.edit),
    delete: descriptor(data.actions?.delete),
  };
  const hasRowActions = can.view || can.edit || can.delete || buttons.length > 0;
  const fieldEntries = Object.entries(formFields);

  return (
    <ContentPanel className="module-page">
      {!onToast && !shared && (
        <Toast message={toast?.message} status={toast?.status} onDismiss={() => setToast(null)} />
      )}

      <TopPanel title={title ?? data.module.name}>
        <TextInput
          className="module-search"
          placeholder="Search…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        {can.create && fieldEntries.length > 0 && (
          <SecondaryButton onClick={openCreate}>New</SecondaryButton>
        )}
        {indexButtons.map((button) => (
          <SecondaryButton key={button.label} onClick={() => button.onClick(load)}>
            {button.label}
          </SecondaryButton>
        ))}
      </TopPanel>

      {panel && (
        <ContentPanel
          className="is-inset"
          as="form"
          onSubmit={submitPanel}
          onClose={closePanel}
          title={
            panel.mode === "create" ? "New record"
              : panel.mode === "edit" ? `Edit ${panel.row?.[primaryKey]}`
              : `Record ${panel.row?.[primaryKey]}`
          }
          footer={
            panel.mode !== "view" && fieldEntries.length > 0 ? (
              <PrimaryButton type="submit" disabled={panel.busy}>
                {panel.busy ? "Saving…" : panel.mode === "create" ? "Create" : "Save"}
              </PrimaryButton>
            ) : null
          }
        >
          {fieldEntries.length === 0 ? (
            <p className="muted">This module declares no form fields.</p>
          ) : (
            <div className="form-grid">
              {fieldEntries.map(([name, config]) => {
                const value = panel.values[name];
                const readOnly = panel.mode === "view";
                const onChange = (next) =>
                  setPanel((p) => ({ ...p, values: { ...p.values, [name]: next } }));

                return (
                  <label className="form-field" key={name}>
                    <InputLabel value={config.label ?? name} required={config.required} />
                    {config.type === "checkbox" ? (
                      <Checkbox checked={value} disabled={readOnly} onChange={(next) => onChange(next)} />
                    ) : config.type === "select" ? (
                      <SelectInput
                        value={value}
                        options={config.options ?? []}
                        disabled={readOnly}
                        placeholder="—"
                        onChange={(e) => onChange(e.target.value)}
                      />
                    ) : (
                      <TextInput
                        type={config.type === "number" ? "number" : "text"}
                        value={value}
                        maxLength={config.max}
                        readOnly={readOnly}
                        onChange={(e) => onChange(e.target.value)}
                      />
                    )}
                    <InputError message={panel.errors?.[name]} />
                  </label>
                );
              })}
            </div>
          )}
        </ContentPanel>
      )}

      {renderBeforeTable?.(data)}

      <TableContainer>
        <Table>
        <TableHead>
          <TableRow>
            {/* Must mirror the body cells below, actions column included, or
                every header sits one column to the left of its data. */}
            {hasRowActions && <HeadData center width="1%">Actions</HeadData>}
            {columns.map((column) => (
              <HeadData
                key={column.key}
                sortable
                sorted={sort.by === column.key}
                direction={sort.dir}
                onSort={() => toggleSort(column.key)}
              >
                {column.label}
              </HeadData>
            ))}
          </TableRow>
        </TableHead>
        <TableBody>
          {rows.map((row) => (
            <TableRow key={row[primaryKey]}>
              {hasRowActions && (
                <RowData center>
                  <RowActions>
                    {can.view && <RowAction type="button" action="view" icon={meta.view.icon} title={meta.view.label} onClick={() => openView(row)} />}
                    {can.edit && <RowAction type="button" action="edit" icon={meta.edit.icon} title={meta.edit.label} onClick={() => useEditRoute ? navigate(`/${path}/edit/${row[primaryKey]}`) : openEdit(row)} />}
                    {can.delete && <RowAction type="button" action="delete" icon={meta.delete.icon} title={meta.delete.label} onClick={() => handleDelete(row)} />}
                    {buttons
                      .filter((button) => rowActionIsVisible(button, row))
                      .map((button, index) => (
                        <RowAction
                          key={`${button.label || button.action || 'row-action'}-${index}`}
                          type="button"
                          action={button.iconAction || button.action || 'view'}
                          icon={button.icon}
                          title={button.label || button.title}
                          onClick={() => handleCustomRowAction(button, row)}
                        />
                      ))}
                  </RowActions>
                </RowData>
              )}
              {columns.map((column) => (
                <RowData key={column.key}>{cell(row, column, defaultCell)}</RowData>
              ))}
            </TableRow>
          ))}
        </TableBody>
        </Table>
      </TableContainer>

      {rows.length === 0 && !loading && <p className="muted">No records.</p>}

      {pagination.last_page > 1 && (
        <div className="module-pager">
          <SecondaryButton disabled={page <= 1} onClick={() => setPage(page - 1)}>
            Prev
          </SecondaryButton>
          <span className="muted">
            Page {pagination.page} of {pagination.last_page} · {pagination.total} records
          </span>
          <SecondaryButton disabled={page >= pagination.last_page} onClick={() => setPage(page + 1)}>
            Next
          </SecondaryButton>
        </div>
      )}

      {renderAfterTable?.(data)}
    </ContentPanel>
  );
}
